### ISSUE TITLE
Fix Voting Bugs

### ISSUE THREAD

**Issue by gchamb** [cat-acronym-team/cat-me-if-you-can#117]
Fix voting bugs because catniss wants a smooth and unbroken gameplay experience.

Tasks:

- [x] Display voting as a heading
- [x] Show prompt answers during voting 
- [x] Dead players should be greyed out during the voting phase
- [x] Dead players shouldn't be able to vote
- [x] Players should be able to vote for themselves
- [x] Highlight who you voted for during the voting phase
- [x] Mobile responsive

Acceptance Criteria:
- Display voting as a heading
- Show prompt answers during voting 
- Dead players should be greyed out during the voting phase
- Dead players shouldn't be able to vote
- Players should be able to vote for themselves
- Highlight who you voted for during the voting phase
- Mobile responsive

**Comment by sjiang1** [comment]
Please explain more about the bug that you are trying to fix.
