### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#26]
Catniss should enter a name before joining or creating a lobby because they want to name themselves instead of random names in the game.

- [x] Display Join and Create Lobby Buttons
- [x] Display Input for Display Name
- [x] Account Dropdown

Acceptance Criteria
- Ability to use buttons to head to different pages
- Ability to enter a display name that will be used later
- If the user tries to join a game without a name they will be asked to provide a name
- Ability to access the drop down that will display different options (account, stats, sign out)
- Validate user doc

**Comment by nstringham** [comment]
~~Should probably add material svelte as a dependency as part of this card~~

**Comment by nstringham** [comment]
the current implementation causes way to many database writes

**Comment by gchamb** [comment]
> the current implementation causes way to many database writes

Are you referring to when the display name is changing it is making updates to their firestore doc?

**Comment by nstringham** [comment]
What does "Validate user attributes" mean?
