### ISSUE TITLE
Allow Catniss to vote other people in game

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#33]
Allows Catniss to cast her vote on others during voting in an established game. so that the player with the most votes can be removed

Catniss should be able to change her vote before the time runs out or until everyone has voted. because new information might come to light last minute which makes her change her mind and because it adds tension to the game.

After the vote a screen will display who was voted out and what role they where. so that Catniss can easily understand what is going on

- [x] User is able to see all the users they can vote for.
- [x] User can click on another user besides themselves to vote for the other user.
- [x] Votes will be pulled from the database and shown below the target (person being voted for) in real time.
- [x] User can change their vote to a different user until a timer runs out, if they do not vote before the timer runs out they abstain.
- [x] Show the user a screen after voting saying who was voted off and what their role was.

**Acceptance Criteria**

- User can vote
- User can see the number of how many times another user has been voted until the timer runs out.
- Shows the voted off user
- Voted off user is marked as dead and can no longer participate in the game
- if there is no user with more votes than anyone else then no one is voted off
- Check for amount of players alive. If the # of cats are <= # of catfish, go to the win/loss page.
- A hacker should not be able to vote more than once or view who voted for who
- a hacker should not be able to make the game end when it has not actually ended
- the winner of the game should be stored into the database in a location everyone can see
- the roles that players have should be visible only after the game as ended

**Comment by gchamb** [comment]
#111
