### ISSUE TITLE
Material Components and CSS Style

### ISSUE THREAD

**Issue by mrjoshua520** [cat-acronym-team/cat-me-if-you-can#83]
Catniss likes dark mode and colorful buttons. Make the app look like a nice modern app using Google's material guidelines. This is because catniss wants to have a pleasant viewing experience 

Tasks:
- [x] get material components imported
- [x] use material for buttons
- [x] use material for text fields
- [x] spend at least 16 hours on styles (including buttons and text fields)

Acceptance Criteria

- The website should have a consistent design/style

**Comment by nstringham** [comment]
1 hour spent on buttons just now

**Comment by nstringham** [comment]
spent another 1.5 hours on sign in buttons

**Comment by nstringham** [comment]
spent half an hour on spinners for game page

**Comment by nstringham** [comment]
spent 2 hours on sign in dialog

**Comment by nstringham** [comment]
spend 1.5 hours last night on chat

**Comment by nstringham** [comment]
spent 2 hours on chat

**Comment by nstringham** [comment]
spent a half hour on spinner

**Comment by nstringham** [comment]
spent 3 hours on chat

**Comment by nstringham** [comment]
5 hours on stalker yesterday
